import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import StyledComponentsRegistry from "./registry";
import GlobalStyleProvider from "@/components/global-style-provider";
import BottomNavBar from "@/components/bottom-nav-bar";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoMono.variable}`}
        style={{
          display: "flex",
          justifyContent: "center",
        }}
      >
        <div
          style={{
            width: "100%",
            maxWidth: "768px",
            minHeight: "100vh",
            boxShadow: "0 0 20px rgba(0,0,0,0.1)",
          }}
        >
          <StyledComponentsRegistry>
            <GlobalStyleProvider>{children}</GlobalStyleProvider>
          </StyledComponentsRegistry>
          <BottomNavBar />
        </div>
      </body>
    </html>
  );
}
